//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3643
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodePlex.SharePointInstaller.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonUIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonUIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodePlex.SharePointInstaller.Resources.CommonUIStrings", typeof(CommonUIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string abortButtonText {
            get {
                return ResourceManager.GetString("abortButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating {0} farm feature(s)..
        /// </summary>
        internal static string activateFarmFeatureMessage {
            get {
                return ResourceManager.GetString("activateFarmFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating feature(s) on {0} site collection(s)..
        /// </summary>
        internal static string activateSiteCollectionFeatureMessage {
            get {
                return ResourceManager.GetString("activateSiteCollectionFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating {0} web application feature(s) on {1} web applications..
        /// </summary>
        internal static string activateWebAppFeatureMessage {
            get {
                return ResourceManager.GetString("activateWebAppFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating feature(s) on {0} site(s)..
        /// </summary>
        internal static string activateWebFeatureMessage {
            get {
                return ResourceManager.GetString("activateWebFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating {0} total activations of {1} feature(s) on {2} location(s)..
        /// </summary>
        internal static string activatingFeaturesMessage {
            get {
                return ResourceManager.GetString("activatingFeaturesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation skipped because feature &quot;{0}&quot; already active on farm..
        /// </summary>
        internal static string ActivatingSkipped_FeatureAlreadyActiveOnFarm {
            get {
                return ResourceManager.GetString("ActivatingSkipped_FeatureAlreadyActiveOnFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation skipped because feature &quot;{0}&quot; already active on site collection: {1}..
        /// </summary>
        internal static string ActivatingSkipped_FeatureAlreadyActiveOnSite {
            get {
                return ResourceManager.GetString("ActivatingSkipped_FeatureAlreadyActiveOnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation skipped because feature &quot;{0}&quot; already active on web: {1}..
        /// </summary>
        internal static string ActivatingSkipped_FeatureAlreadyActiveOnWeb {
            get {
                return ResourceManager.GetString("ActivatingSkipped_FeatureAlreadyActiveOnWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation skipped because feature &quot;{0}&quot; already active on web application: {1}..
        /// </summary>
        internal static string ActivatingSkipped_FeatureAlreadyActiveOnWebApp {
            get {
                return ResourceManager.GetString("ActivatingSkipped_FeatureAlreadyActiveOnWebApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied! Could not add solution to the SharePoint farm..
        /// </summary>
        internal static string addSolutionAccessError {
            get {
                return ResourceManager.GetString("addSolutionAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you are logged in as SharePoint Administrator or Domain Administrator on the server..
        /// </summary>
        internal static string addSolutionAccessErrorWinServer2003Solution {
            get {
                return ResourceManager.GetString("addSolutionAccessErrorWinServer2003Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you are logged in as SharePoint Administrator or Domain Administrator on the server. Also, make sure to turn off Windows User Account Control..
        /// </summary>
        internal static string addSolutionAccessErrorWinServer2008Solution {
            get {
                return ResourceManager.GetString("addSolutionAccessErrorWinServer2008Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding solution to the SharePoint solution store..
        /// </summary>
        internal static string addSolutionCommand {
            get {
                return ResourceManager.GetString("addSolutionCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do NOT have permission to install and deploy SharePoint solutions!.
        /// </summary>
        internal static string adminRightsCheckErrorText {
            get {
                return ResourceManager.GetString("adminRightsCheckErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have permission to install and deploy SharePoint solutions..
        /// </summary>
        internal static string adminRightsCheckOkText {
            get {
                return ResourceManager.GetString("adminRightsCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have permission to install and deploy SharePoint solutions?.
        /// </summary>
        internal static string adminRightsCheckQuestionText {
            get {
                return ResourceManager.GetString("adminRightsCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows SharePoint Services Administration service is NOT started!.
        /// </summary>
        internal static string adminServiceCheckErrorText {
            get {
                return ResourceManager.GetString("adminServiceCheckErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows SharePoint Services Administration service is started..
        /// </summary>
        internal static string adminServiceCheckOkText {
            get {
                return ResourceManager.GetString("adminServiceCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the Windows SharePoint Services Administration service started?.
        /// </summary>
        internal static string adminServiceCheckQuestionText {
            get {
                return ResourceManager.GetString("adminServiceCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review currently activated locations if desired.
        /// </summary>
        internal static string controlSubTitleActivations {
            get {
                return ResourceManager.GetString("controlSubTitleActivations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the solution is installed.
        /// </summary>
        internal static string controlSubTitleInstalling {
            get {
                return ResourceManager.GetString("controlSubTitleInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read the following license agreement carefully.
        /// </summary>
        internal static string controlSubTitleLicense {
            get {
                return ResourceManager.GetString("controlSubTitleLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string controlSubTitleOptions {
            get {
                return ResourceManager.GetString("controlSubTitleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the operation you wish to perform.
        /// </summary>
        internal static string controlSubTitleSelectOperation {
            get {
                return ResourceManager.GetString("controlSubTitleSelectOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one or more web applications / site collections.
        /// </summary>
        internal static string controlSubTitleSiteDeployment {
            get {
                return ResourceManager.GetString("controlSubTitleSiteDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if {SolutionTitle} can be installed from this machine.
        /// </summary>
        internal static string controlSubTitleSystemCheck {
            get {
                return ResourceManager.GetString("controlSubTitleSystemCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one or more web applications.
        /// </summary>
        internal static string controlSubTitleWebApplicationDeployment {
            get {
                return ResourceManager.GetString("controlSubTitleWebApplicationDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the {SolutionTitle} setup wizard.
        /// </summary>
        internal static string controlSubTitleWelcome {
            get {
                return ResourceManager.GetString("controlSubTitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Currently Activated Locations.
        /// </summary>
        internal static string controlSummaryActivations {
            get {
                return ResourceManager.GetString("controlSummaryActivations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string controlSummaryCompleted {
            get {
                return ResourceManager.GetString("controlSummaryCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string controlSummaryFinished {
            get {
                return ResourceManager.GetString("controlSummaryFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform Operation.
        /// </summary>
        internal static string controlSummaryInstalling {
            get {
                return ResourceManager.GetString("controlSummaryInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string controlSummaryWelcome {
            get {
                return ResourceManager.GetString("controlSummaryWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Activated Instances.
        /// </summary>
        internal static string controlTitleActivations {
            get {
                return ResourceManager.GetString("controlTitleActivations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string controlTitleInstalling {
            get {
                return ResourceManager.GetString("controlTitleInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End-User License Agreement.
        /// </summary>
        internal static string controlTitleLicense {
            get {
                return ResourceManager.GetString("controlTitleLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Options.
        /// </summary>
        internal static string controlTitleOptions {
            get {
                return ResourceManager.GetString("controlTitleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair or Remove.
        /// </summary>
        internal static string controlTitleRepairRemove {
            get {
                return ResourceManager.GetString("controlTitleRepairRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Collection Deployment Targets.
        /// </summary>
        internal static string controlTitleSiteDeployment {
            get {
                return ResourceManager.GetString("controlTitleSiteDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Check.
        /// </summary>
        internal static string controlTitleSystemCheck {
            get {
                return ResourceManager.GetString("controlTitleSystemCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade or Remove.
        /// </summary>
        internal static string controlTitleUpgradeRemove {
            get {
                return ResourceManager.GetString("controlTitleUpgradeRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Application Deployment Targets.
        /// </summary>
        internal static string controlTitleWebApplicationDeployment {
            get {
                return ResourceManager.GetString("controlTitleWebApplicationDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SolutionTitle}.
        /// </summary>
        internal static string controlTitleWelcome {
            get {
                return ResourceManager.GetString("controlTitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating job for deploying the solution to web applications..
        /// </summary>
        internal static string createDeploymentJobCommand {
            get {
                return ResourceManager.GetString("createDeploymentJobCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating job for retracting the solution from all web applications..
        /// </summary>
        internal static string createRetractionJobCommand {
            get {
                return ResourceManager.GetString("createRetractionJobCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating job for upgrading the solution on all applicable web applications..
        /// </summary>
        internal static string createUpgradeJobCommand {
            get {
                return ResourceManager.GetString("createUpgradeJobCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating {0} farm feature(s)..
        /// </summary>
        internal static string deactivateFarmFeatureMessage {
            get {
                return ResourceManager.GetString("deactivateFarmFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating {0} feature(s) on {1} site collection(s)..
        /// </summary>
        internal static string deactivateSiteCollectionFeatureMessage {
            get {
                return ResourceManager.GetString("deactivateSiteCollectionFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating {0} web application feature(s) on {1} web applications..
        /// </summary>
        internal static string deactivateWebAppFeatureMessage {
            get {
                return ResourceManager.GetString("deactivateWebAppFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating {0} feature(s) on {1} site(s)..
        /// </summary>
        internal static string deactivateWebFeatureMessage {
            get {
                return ResourceManager.GetString("deactivateWebFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating {0} total activations of {1} feature(s) on {2} location(s)..
        /// </summary>
        internal static string deactivatingFeaturesMessage {
            get {
                return ResourceManager.GetString("deactivatingFeaturesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivation skipped because feature &quot;{0}&quot; already active on farm..
        /// </summary>
        internal static string DeactivatingSkipped_FeatureAlreadyActiveOnFarm {
            get {
                return ResourceManager.GetString("DeactivatingSkipped_FeatureAlreadyActiveOnFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivation skipped because feature &quot;{0}&quot; already active on site collection: {1}..
        /// </summary>
        internal static string DeactivatingSkipped_FeatureAlreadyActiveOnSite {
            get {
                return ResourceManager.GetString("DeactivatingSkipped_FeatureAlreadyActiveOnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivation skipped because feature &quot;{0}&quot; already active on web: {1}..
        /// </summary>
        internal static string DeactivatingSkipped_FeatureAlreadyActiveOnWeb {
            get {
                return ResourceManager.GetString("DeactivatingSkipped_FeatureAlreadyActiveOnWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivation skipped because feature &quot;{0}&quot; already active on web application: {1}..
        /// </summary>
        internal static string DeactivatingSkipped_FeatureAlreadyActiveOnWebApp {
            get {
                return ResourceManager.GetString("DeactivatingSkipped_FeatureAlreadyActiveOnWebApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors detected. Rolling back all operations..
        /// </summary>
        internal static string descriptionLabelTextErrorsDetected {
            get {
                return ResourceManager.GetString("descriptionLabelTextErrorsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled! Rolling back all operations..
        /// </summary>
        internal static string descriptionLabelTextOperationCanceled {
            get {
                return ResourceManager.GetString("descriptionLabelTextOperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback completed with {0} errors. Please see log file for details..
        /// </summary>
        internal static string descriptionLabelTextRollbackError {
            get {
                return ResourceManager.GetString("descriptionLabelTextRollbackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback successfully completed..
        /// </summary>
        internal static string descriptionLabelTextRollbackSuccess {
            get {
                return ResourceManager.GetString("descriptionLabelTextRollbackSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All operations successfully completed..
        /// </summary>
        internal static string descriptionLabelTextSuccess {
            get {
                return ResourceManager.GetString("descriptionLabelTextSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking features as specified in config.
        /// </summary>
        internal static string featuresCheckQuestionText {
            get {
                return ResourceManager.GetString("featuresCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed features specified: {0}.
        /// </summary>
        internal static string featuresInstalledText {
            get {
                return ResourceManager.GetString("featuresInstalledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified features, total={0}, new={1}, installed={2}, other soln={3}, no soln={4}.
        /// </summary>
        internal static string featuresMixedText {
            get {
                return ResourceManager.GetString("featuresMixedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New features specified: {0}.
        /// </summary>
        internal static string featuresNewText {
            get {
                return ResourceManager.GetString("featuresNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more documentation on how to use {SolutionTitle} click here..
        /// </summary>
        internal static string finishedLinkText {
            get {
                return ResourceManager.GetString("finishedLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to configure {SolutionTitle} for {0}..
        /// </summary>
        internal static string finishedLinkTextSiteCollection {
            get {
                return ResourceManager.GetString("finishedLinkTextSiteCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to configure {SolutionTitle} for {0}..
        /// </summary>
        internal static string finishedLinkTextSsp {
            get {
                return ResourceManager.GetString("finishedLinkTextSsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished installing {SolutionTitle}.
        /// </summary>
        internal static string finishedSubTitle {
            get {
                return ResourceManager.GetString("finishedSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string finishedTitle {
            get {
                return ResourceManager.GetString("finishedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Failed.
        /// </summary>
        internal static string installError {
            get {
                return ResourceManager.GetString("installError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. Could not read the Windows Registry key &apos;{0}&apos;.
        /// </summary>
        internal static string installExceptionAccessDenied {
            get {
                return ResourceManager.GetString("installExceptionAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error! Invalid Solution id..
        /// </summary>
        internal static string installExceptionConfigurationInvalidId {
            get {
                return ResourceManager.GetString("installExceptionConfigurationInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error! Missing Solution id..
        /// </summary>
        internal static string installExceptionConfigurationNoId {
            get {
                return ResourceManager.GetString("installExceptionConfigurationNoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error! No Solution file was specified in setup.exe.config.
        /// </summary>
        internal static string installExceptionConfigurationNoWsp {
            get {
                return ResourceManager.GetString("installExceptionConfigurationNoWsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint was unable to connect to the database..
        /// </summary>
        internal static string installExceptionDatabase {
            get {
                return ResourceManager.GetString("installExceptionDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another deployment job for this solution is currently running..
        /// </summary>
        internal static string installExceptionDuplicateJob {
            get {
                return ResourceManager.GetString("installExceptionDuplicateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the specified solution file &apos;{0}&apos;.
        /// </summary>
        internal static string installExceptionFileNotFound {
            get {
                return ResourceManager.GetString("installExceptionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout error.
        /// </summary>
        internal static string installExceptionTimeout {
            get {
                return ResourceManager.GetString("installExceptionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {SolutionTitle} is installed.
        /// </summary>
        internal static string installSubTitle {
            get {
                return ResourceManager.GetString("installSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Successfully Completed.
        /// </summary>
        internal static string installSuccess {
            get {
                return ResourceManager.GetString("installSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string installTitle {
            get {
                return ResourceManager.GetString("installTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process [{0}]..
        /// </summary>
        internal static string linkLabelDialogText {
            get {
                return ResourceManager.GetString("linkLabelDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** ERROR *****.
        /// </summary>
        internal static string logError {
            get {
                return ResourceManager.GetString("logError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** FEATURE ACTIVATION *****.
        /// </summary>
        internal static string logFeatureActivate {
            get {
                return ResourceManager.GetString("logFeatureActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** FEATURE DEACTIVATION *****.
        /// </summary>
        internal static string logFeatureDeactivate {
            get {
                return ResourceManager.GetString("logFeatureDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No features specified..
        /// </summary>
        internal static string logNoFeaturesSpecified {
            get {
                return ResourceManager.GetString("logNoFeaturesSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No locations for activation/deactivation..
        /// </summary>
        internal static string logNoLocationsForActivationDeactivation {
            get {
                return ResourceManager.GetString("logNoLocationsForActivationDeactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No site collections have feature activated..
        /// </summary>
        internal static string logNoSiteCollectionsFeatured {
            get {
                return ResourceManager.GetString("logNoSiteCollectionsFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No site collections specified..
        /// </summary>
        internal static string logNoSiteCollectionsSpecified {
            get {
                return ResourceManager.GetString("logNoSiteCollectionsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sites have feature activated..
        /// </summary>
        internal static string logNoWebsFeatured {
            get {
                return ResourceManager.GetString("logNoWebsFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** SOLUTION RETRACTION *****.
        /// </summary>
        internal static string logRetract {
            get {
                return ResourceManager.GetString("logRetract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** SOLUTION UPGRADE *****.
        /// </summary>
        internal static string logUpgrade {
            get {
                return ResourceManager.GetString("logUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Please correct the above errors before installing {SolutionTitle}..
        /// </summary>
        internal static string messageLabelTextError {
            get {
                return ResourceManager.GetString("messageLabelTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All checks succeeded. Please click Next to proceed with the installation..
        /// </summary>
        internal static string messageLabelTextSuccess {
            get {
                return ResourceManager.GetString("messageLabelTextSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Server is NOT installed!.
        /// </summary>
        internal static string mossCheckErrorText {
            get {
                return ResourceManager.GetString("mossCheckErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Server is installed..
        /// </summary>
        internal static string mossCheckOkText {
            get {
                return ResourceManager.GetString("mossCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is SharePoint Server installed?.
        /// </summary>
        internal static string mossCheckQuestionText {
            get {
                return ResourceManager.GetString("mossCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering version number..
        /// </summary>
        internal static string registerVersionNumberCommand {
            get {
                return ResourceManager.GetString("registerVersionNumberCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing solution from the SharePoint solution store..
        /// </summary>
        internal static string removeSolutionCommand {
            get {
                return ResourceManager.GetString("removeSolutionCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Failed.
        /// </summary>
        internal static string repairError {
            get {
                return ResourceManager.GetString("repairError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {SolutionTitle} is repaired.
        /// </summary>
        internal static string repairSubTitle {
            get {
                return ResourceManager.GetString("repairSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Successfully Completed.
        /// </summary>
        internal static string repairSuccess {
            get {
                return ResourceManager.GetString("repairSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairing.
        /// </summary>
        internal static string repairTitle {
            get {
                return ResourceManager.GetString("repairTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;cannot access root web - access denied&gt;.
        /// </summary>
        internal static string rootWebTitleAccessDenied {
            get {
                return ResourceManager.GetString("rootWebTitleAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access error on site collection {0}..
        /// </summary>
        internal static string siteCollectionAccessError {
            get {
                return ResourceManager.GetString("siteCollectionAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping Site Selection because no featureid specified..
        /// </summary>
        internal static string skippingSiteSelectionNoFeature {
            get {
                return ResourceManager.GetString("skippingSiteSelectionNoFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error detecting {SolutionTitle}!.
        /// </summary>
        internal static string solutionCheckErrorText {
            get {
                return ResourceManager.GetString("solutionCheckErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SolutionTitle} not installed.
        /// </summary>
        internal static string solutionCheckOkText {
            get {
                return ResourceManager.GetString("solutionCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SolutionTitle} is already installed..
        /// </summary>
        internal static string solutionCheckOkTextInstalled {
            get {
                return ResourceManager.GetString("solutionCheckOkTextInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SolutionTitle} is not installed..
        /// </summary>
        internal static string solutionCheckOkTextNotInstalled {
            get {
                return ResourceManager.GetString("solutionCheckOkTextNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting {SolutionTitle}.
        /// </summary>
        internal static string solutionCheckQuestionText {
            get {
                return ResourceManager.GetString("solutionCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution file found..
        /// </summary>
        internal static string solutionFileCheckOkText {
            get {
                return ResourceManager.GetString("solutionFileCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the solution file exist?.
        /// </summary>
        internal static string solutionFileCheckQuestionText {
            get {
                return ResourceManager.GetString("solutionFileCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows SharePoint Services Timer service is NOT started!.
        /// </summary>
        internal static string timerServiceCheckErrorText {
            get {
                return ResourceManager.GetString("timerServiceCheckErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows SharePoint Services Timer service is started..
        /// </summary>
        internal static string timerServiceCheckOkText {
            get {
                return ResourceManager.GetString("timerServiceCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the Windows SharePoint Services Timer service started?.
        /// </summary>
        internal static string timerServiceCheckQuestionText {
            get {
                return ResourceManager.GetString("timerServiceCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Failed.
        /// </summary>
        internal static string uninstallError {
            get {
                return ResourceManager.GetString("uninstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {SolutionTitle} is removed.
        /// </summary>
        internal static string uninstallSubTitle {
            get {
                return ResourceManager.GetString("uninstallSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Successfully Completed.
        /// </summary>
        internal static string uninstallSuccess {
            get {
                return ResourceManager.GetString("uninstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling.
        /// </summary>
        internal static string uninstallTitle {
            get {
                return ResourceManager.GetString("uninstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistering version number..
        /// </summary>
        internal static string unregisterVersionNumberCommand {
            get {
                return ResourceManager.GetString("unregisterVersionNumberCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Failed.
        /// </summary>
        internal static string upgradeError {
            get {
                return ResourceManager.GetString("upgradeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {SolutionTitle} is upgraded.
        /// </summary>
        internal static string upgradeSubTitle {
            get {
                return ResourceManager.GetString("upgradeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Successfully Completed.
        /// </summary>
        internal static string upgradeSuccess {
            get {
                return ResourceManager.GetString("upgradeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading.
        /// </summary>
        internal static string upgradeTitle {
            get {
                return ResourceManager.GetString("upgradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint version NOT compatible: {0}!.
        /// </summary>
        internal static string versionCheckErrorText {
            get {
                return ResourceManager.GetString("versionCheckErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint version compatible: {0}..
        /// </summary>
        internal static string versionCheckOkText {
            get {
                return ResourceManager.GetString("versionCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint version between &apos;{0}&apos; and &apos;{1}&apos;?.
        /// </summary>
        internal static string versionCheckQuestionText {
            get {
                return ResourceManager.GetString("versionCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for solution deployment job to complete. Press Abort to stop..
        /// </summary>
        internal static string waitForSolutionDeployment {
            get {
                return ResourceManager.GetString("waitForSolutionDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for solution retraction job to complete. Press Abort to stop..
        /// </summary>
        internal static string waitForSolutionRetraction {
            get {
                return ResourceManager.GetString("waitForSolutionRetraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for solution upgrade job to complete. Press Abort to stop..
        /// </summary>
        internal static string waitForSolutionUpgrade {
            get {
                return ResourceManager.GetString("waitForSolutionUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying to web application(s): {0}..
        /// </summary>
        internal static string WebApplicationDeploymentLogMessage {
            get {
                return ResourceManager.GetString("WebApplicationDeploymentLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Foundation/Services is NOT installed!.
        /// </summary>
        internal static string wssCheckErrorText {
            get {
                return ResourceManager.GetString("wssCheckErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Foundation/Services is installed..
        /// </summary>
        internal static string wssCheckOkText {
            get {
                return ResourceManager.GetString("wssCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is SharePoint Foundation/Services installed?.
        /// </summary>
        internal static string wssCheckQuestionText {
            get {
                return ResourceManager.GetString("wssCheckQuestionText", resourceCulture);
            }
        }
    }
}
