//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodePlex.SharePointInstaller.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonUIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonUIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodePlex.SharePointInstaller.Resources.CommonUIStrings", typeof(CommonUIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string AbortButtonText {
            get {
                return ResourceManager.GetString("AbortButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating farm feature(s)..
        /// </summary>
        internal static string ActivateFarmFeatureCmd {
            get {
                return ResourceManager.GetString("ActivateFarmFeatureCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating feature(s) on {0} site collection{1}..
        /// </summary>
        internal static string ActivateSiteCollectionFeatureCommand {
            get {
                return ResourceManager.GetString("ActivateSiteCollectionFeatureCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding solution to the SharePoint solution store..
        /// </summary>
        internal static string AddSolutionCmd {
            get {
                return ResourceManager.GetString("AddSolutionCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied! Could not add solution to the SharePoint farm..
        /// </summary>
        internal static string AddSolutionCmdAccessError {
            get {
                return ResourceManager.GetString("AddSolutionCmdAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you are logged in as SharePoint Administrator or Domain Administrator on the server..
        /// </summary>
        internal static string AddSolutionCmdAccessErrorWinServer2003Solution {
            get {
                return ResourceManager.GetString("AddSolutionCmdAccessErrorWinServer2003Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you are logged in as SharePoint Administrator or Domain Administrator on the server. Also, make sure to turn off Windows User Account Control..
        /// </summary>
        internal static string AddSolutionCmdAccessErrorWinServer2008Solution {
            get {
                return ResourceManager.GetString("AddSolutionCmdAccessErrorWinServer2008Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do NOT have permission to install and deploy SharePoint solutions!.
        /// </summary>
        internal static string AdminRightsCheckErrorText {
            get {
                return ResourceManager.GetString("AdminRightsCheckErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have permission to install and deploy SharePoint solutions..
        /// </summary>
        internal static string AdminRightsCheckOkText {
            get {
                return ResourceManager.GetString("AdminRightsCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have permission to install and deploy SharePoint solutions?.
        /// </summary>
        internal static string AdminRightsCheckQuestionText {
            get {
                return ResourceManager.GetString("AdminRightsCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows SharePoint Services Administration service is NOT started!.
        /// </summary>
        internal static string AdminServiceCheckErrorText {
            get {
                return ResourceManager.GetString("AdminServiceCheckErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SharePoint Foundation 2010 Administration service is NOT started!.
        /// </summary>
        internal static string AdminServiceCheckErrorText2010 {
            get {
                return ResourceManager.GetString("AdminServiceCheckErrorText2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows SharePoint Services Administration service is started..
        /// </summary>
        internal static string AdminServiceCheckOkText {
            get {
                return ResourceManager.GetString("AdminServiceCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SharePoint Foundation 2010 Administration service is started..
        /// </summary>
        internal static string AdminServiceCheckOkText2010 {
            get {
                return ResourceManager.GetString("AdminServiceCheckOkText2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the Windows SharePoint Services Administration service started?.
        /// </summary>
        internal static string AdminServiceCheckQuestionText {
            get {
                return ResourceManager.GetString("AdminServiceCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the SharePoint Foundation 2010 Administration service started?.
        /// </summary>
        internal static string AdminServiceCheckQuestionText2010 {
            get {
                return ResourceManager.GetString("AdminServiceCheckQuestionText2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to instantiate the referenced command ({0}). Please check the config file..
        /// </summary>
        internal static string CommandsCheckInstantiateErrorText {
            get {
                return ResourceManager.GetString("CommandsCheckInstantiateErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there any post-install commands to run?.
        /// </summary>
        internal static string CommandsCheckQuestionText {
            get {
                return ResourceManager.GetString("CommandsCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No post-install commands are present..
        /// </summary>
        internal static string CommandsCheckSkipQuestionText {
            get {
                return ResourceManager.GetString("CommandsCheckSkipQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-install command(s) syntax is valid..
        /// </summary>
        internal static string CommandsCheckSuccessText {
            get {
                return ResourceManager.GetString("CommandsCheckSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax check failed for the command {0}: {1}. Please check the config file..
        /// </summary>
        internal static string CommandsCheckSyntaxErrorText {
            get {
                return ResourceManager.GetString("CommandsCheckSyntaxErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one or more web applications.
        /// </summary>
        internal static string ControlSubTitleFarmDeployment {
            get {
                return ResourceManager.GetString("ControlSubTitleFarmDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the solution is installed.
        /// </summary>
        internal static string ControlSubTitleInstalling {
            get {
                return ResourceManager.GetString("ControlSubTitleInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read the following license agreement carefully.
        /// </summary>
        internal static string ControlSubTitleLicense {
            get {
                return ResourceManager.GetString("ControlSubTitleLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ControlSubTitleOptions {
            get {
                return ResourceManager.GetString("ControlSubTitleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the operation you wish to perform.
        /// </summary>
        internal static string ControlSubTitleSelectOperation {
            get {
                return ResourceManager.GetString("ControlSubTitleSelectOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one or more web applications / site collections.
        /// </summary>
        internal static string ControlSubTitleSiteDeployment {
            get {
                return ResourceManager.GetString("ControlSubTitleSiteDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if {SolutionTitle} can be installed from this machine.
        /// </summary>
        internal static string ControlSubTitleSystemCheck {
            get {
                return ResourceManager.GetString("ControlSubTitleSystemCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the {SolutionTitle} setup wizard.
        /// </summary>
        internal static string ControlSubTitleWelcome {
            get {
                return ResourceManager.GetString("ControlSubTitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm Deployment Targets.
        /// </summary>
        internal static string ControlTitleFarmDeployment {
            get {
                return ResourceManager.GetString("ControlTitleFarmDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string ControlTitleInstalling {
            get {
                return ResourceManager.GetString("ControlTitleInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End-User License Agreement.
        /// </summary>
        internal static string ControlTitleLicense {
            get {
                return ResourceManager.GetString("ControlTitleLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Options.
        /// </summary>
        internal static string ControlTitleOptions {
            get {
                return ResourceManager.GetString("ControlTitleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair or Remove.
        /// </summary>
        internal static string ControlTitleRepairRemove {
            get {
                return ResourceManager.GetString("ControlTitleRepairRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Collection Deployment Targets.
        /// </summary>
        internal static string ControlTitleSiteDeployment {
            get {
                return ResourceManager.GetString("ControlTitleSiteDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Check.
        /// </summary>
        internal static string ControlTitleSystemCheck {
            get {
                return ResourceManager.GetString("ControlTitleSystemCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade or Remove.
        /// </summary>
        internal static string ControlTitleUpgradeRemove {
            get {
                return ResourceManager.GetString("ControlTitleUpgradeRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SolutionTitle}.
        /// </summary>
        internal static string ControlTitleWelcome {
            get {
                return ResourceManager.GetString("ControlTitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating farm feature(s)..
        /// </summary>
        internal static string DeactivateFarmFeatureCommand {
            get {
                return ResourceManager.GetString("DeactivateFarmFeatureCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating site collection feature(s)..
        /// </summary>
        internal static string DeactivateSiteCollectionFeatureCommand {
            get {
                return ResourceManager.GetString("DeactivateSiteCollectionFeatureCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating job for deploying the solution to all web applications..
        /// </summary>
        internal static string DeploySolutionCmd {
            get {
                return ResourceManager.GetString("DeploySolutionCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors detected. Rolling back all operations..
        /// </summary>
        internal static string DescriptionLabelTextErrorsDetected {
            get {
                return ResourceManager.GetString("DescriptionLabelTextErrorsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled! Rolling back all operations..
        /// </summary>
        internal static string DescriptionLabelTextOperationCanceled {
            get {
                return ResourceManager.GetString("DescriptionLabelTextOperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback completed with {0} errors. Please see log file for details..
        /// </summary>
        internal static string DescriptionLabelTextRollbackError {
            get {
                return ResourceManager.GetString("DescriptionLabelTextRollbackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback successfully completed..
        /// </summary>
        internal static string DescriptionLabelTextRollbackSuccess {
            get {
                return ResourceManager.GetString("DescriptionLabelTextRollbackSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All operations successfully completed..
        /// </summary>
        internal static string DescriptionLabelTextSuccess {
            get {
                return ResourceManager.GetString("DescriptionLabelTextSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running custom post-install command(s)..
        /// </summary>
        internal static string ExecuteCustomCommandDescription {
            get {
                return ResourceManager.GetString("ExecuteCustomCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more documentation on how to use {SolutionTitle} click here..
        /// </summary>
        internal static string FinishedLinkText {
            get {
                return ResourceManager.GetString("FinishedLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to configure {SolutionTitle} for {0}..
        /// </summary>
        internal static string FinishedLinkTextSiteCollection {
            get {
                return ResourceManager.GetString("FinishedLinkTextSiteCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to configure {SolutionTitle} for {0}..
        /// </summary>
        internal static string FinishedLinkTextSsp {
            get {
                return ResourceManager.GetString("FinishedLinkTextSsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished installing {SolutionTitle}.
        /// </summary>
        internal static string FinishedSubTitle {
            get {
                return ResourceManager.GetString("FinishedSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string FinishedTitle {
            get {
                return ResourceManager.GetString("FinishedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** Installing &apos;{0}&apos; solution... {1} *****.
        /// </summary>
        internal static string InstallBegin {
            get {
                return ResourceManager.GetString("InstallBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** Installation Failed {0} *****.
        /// </summary>
        internal static string InstallError {
            get {
                return ResourceManager.GetString("InstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. Could not read the Windows Registry key &apos;{0}&apos;.
        /// </summary>
        internal static string InstallExceptionAccessDenied {
            get {
                return ResourceManager.GetString("InstallExceptionAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error! Invalid Solution id..
        /// </summary>
        internal static string InstallExceptionConfigurationInvalidId {
            get {
                return ResourceManager.GetString("InstallExceptionConfigurationInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error! Missing Solution id..
        /// </summary>
        internal static string InstallExceptionConfigurationNoId {
            get {
                return ResourceManager.GetString("InstallExceptionConfigurationNoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error! No Solution file was specified in setup.exe.config.
        /// </summary>
        internal static string InstallExceptionConfigurationNoWsp {
            get {
                return ResourceManager.GetString("InstallExceptionConfigurationNoWsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint was unable to connect to the database..
        /// </summary>
        internal static string InstallExceptionDatabase {
            get {
                return ResourceManager.GetString("InstallExceptionDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another deployment job for this solution is currently running..
        /// </summary>
        internal static string InstallExceptionDuplicateJob {
            get {
                return ResourceManager.GetString("InstallExceptionDuplicateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the specified solution file &apos;{0}&apos;.
        /// </summary>
        internal static string InstallExceptionFileNotFound {
            get {
                return ResourceManager.GetString("InstallExceptionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout error.
        /// </summary>
        internal static string InstallExceptionTimeout {
            get {
                return ResourceManager.GetString("InstallExceptionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {SolutionTitle} is installed.
        /// </summary>
        internal static string InstallSubTitle {
            get {
                return ResourceManager.GetString("InstallSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** Installation Successfully Completed {0} *****.
        /// </summary>
        internal static string InstallSuccess {
            get {
                return ResourceManager.GetString("InstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string InstallTitle {
            get {
                return ResourceManager.GetString("InstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process [{0}]..
        /// </summary>
        internal static string LinkLabelDialogText {
            get {
                return ResourceManager.GetString("LinkLabelDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding solution....
        /// </summary>
        internal static string LogAdd {
            get {
                return ResourceManager.GetString("LogAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying solution....
        /// </summary>
        internal static string LogDeployment {
            get {
                return ResourceManager.GetString("LogDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** ERROR *****.
        /// </summary>
        internal static string LogError {
            get {
                return ResourceManager.GetString("LogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating features....
        /// </summary>
        internal static string LogFeatureActivate {
            get {
                return ResourceManager.GetString("LogFeatureActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating features....
        /// </summary>
        internal static string LogFeatureDeactivate {
            get {
                return ResourceManager.GetString("LogFeatureDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing solution....
        /// </summary>
        internal static string LogRemove {
            get {
                return ResourceManager.GetString("LogRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retracting solution....
        /// </summary>
        internal static string LogRetract {
            get {
                return ResourceManager.GetString("LogRetract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading solution....
        /// </summary>
        internal static string LogUpgrade {
            get {
                return ResourceManager.GetString("LogUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisites check failed..
        /// </summary>
        internal static string MessageLabelPreCheckError {
            get {
                return ResourceManager.GetString("MessageLabelPreCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Please correct the above errors before installing {SolutionTitle}..
        /// </summary>
        internal static string MessageLabelTextError {
            get {
                return ResourceManager.GetString("MessageLabelTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All checks succeeded. Please click Next to proceed with the installation..
        /// </summary>
        internal static string MessageLabelTextSuccess {
            get {
                return ResourceManager.GetString("MessageLabelTextSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Office SharePoint Server 2007 is NOT installed!.
        /// </summary>
        internal static string MossCheckErrorText {
            get {
                return ResourceManager.GetString("MossCheckErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Server 2010 is NOT installed!.
        /// </summary>
        internal static string MossCheckErrorText2010 {
            get {
                return ResourceManager.GetString("MossCheckErrorText2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Office SharePoint Server 2007 is installed..
        /// </summary>
        internal static string MossCheckOkText {
            get {
                return ResourceManager.GetString("MossCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Server 2010 is installed..
        /// </summary>
        internal static string MossCheckOkText2010 {
            get {
                return ResourceManager.GetString("MossCheckOkText2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Microsoft Office SharePoint Server 2007 installed?.
        /// </summary>
        internal static string MossCheckQuestionText {
            get {
                return ResourceManager.GetString("MossCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is SharePoint Server 2010 installed?.
        /// </summary>
        internal static string MossCheckQuestionText2010 {
            get {
                return ResourceManager.GetString("MossCheckQuestionText2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering version number..
        /// </summary>
        internal static string RegisterVersionNumberCommand {
            get {
                return ResourceManager.GetString("RegisterVersionNumberCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing solution from the SharePoint solution store..
        /// </summary>
        internal static string RemoveSolutionCmd {
            get {
                return ResourceManager.GetString("RemoveSolutionCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** Repairing &apos;{0}&apos; solution... {1} *****.
        /// </summary>
        internal static string RepairBegin {
            get {
                return ResourceManager.GetString("RepairBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** Repair Failed {0} *****.
        /// </summary>
        internal static string RepairError {
            get {
                return ResourceManager.GetString("RepairError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {SolutionTitle} is repaired.
        /// </summary>
        internal static string RepairSubTitle {
            get {
                return ResourceManager.GetString("RepairSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** Repair Successfully Completed {0} *****.
        /// </summary>
        internal static string RepairSuccess {
            get {
                return ResourceManager.GetString("RepairSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairing.
        /// </summary>
        internal static string RepairTitle {
            get {
                return ResourceManager.GetString("RepairTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating job for retracting the solution from all web applications..
        /// </summary>
        internal static string RetractSolutionCmd {
            get {
                return ResourceManager.GetString("RetractSolutionCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;cannot access root web - access denied&gt;.
        /// </summary>
        internal static string RootWebTitleAccessDenied {
            get {
                return ResourceManager.GetString("RootWebTitleAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error detecting {SolutionTitle}!.
        /// </summary>
        internal static string SolutionCheckErrorText {
            get {
                return ResourceManager.GetString("SolutionCheckErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SolutionTitle} not installed.
        /// </summary>
        internal static string SolutionCheckOkText {
            get {
                return ResourceManager.GetString("SolutionCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SolutionTitle} is already installed..
        /// </summary>
        internal static string SolutionCheckOkTextInstalled {
            get {
                return ResourceManager.GetString("SolutionCheckOkTextInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SolutionTitle} is not installed..
        /// </summary>
        internal static string SolutionCheckOkTextNotInstalled {
            get {
                return ResourceManager.GetString("SolutionCheckOkTextNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting {SolutionTitle}.
        /// </summary>
        internal static string SolutionCheckQuestionText {
            get {
                return ResourceManager.GetString("SolutionCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution file found..
        /// </summary>
        internal static string SolutionFileCheckOkText {
            get {
                return ResourceManager.GetString("SolutionFileCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the solution file exist?.
        /// </summary>
        internal static string SolutionFileCheckQuestionText {
            get {
                return ResourceManager.GetString("SolutionFileCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Solution file was specified in setup.exe.config. Only removal is available..
        /// </summary>
        internal static string SolutionFileValidatorQuestionText {
            get {
                return ResourceManager.GetString("SolutionFileValidatorQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows SharePoint Services Timer service is NOT started!.
        /// </summary>
        internal static string TimerServiceCheckErrorText {
            get {
                return ResourceManager.GetString("TimerServiceCheckErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SharePoint Foundation 2010 Timer service is NOT started!.
        /// </summary>
        internal static string TimerServiceCheckErrorText2010 {
            get {
                return ResourceManager.GetString("TimerServiceCheckErrorText2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows SharePoint Services Timer service is started..
        /// </summary>
        internal static string TimerServiceCheckOkText {
            get {
                return ResourceManager.GetString("TimerServiceCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SharePoint Foundation 2010 Timer service is started..
        /// </summary>
        internal static string TimerServiceCheckOkText2010 {
            get {
                return ResourceManager.GetString("TimerServiceCheckOkText2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the Windows SharePoint Services Timer service started?.
        /// </summary>
        internal static string TimerServiceCheckQuestionText {
            get {
                return ResourceManager.GetString("TimerServiceCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the SharePoint Foundation 2010 Timer service started?.
        /// </summary>
        internal static string TimerServiceCheckQuestionText2010 {
            get {
                return ResourceManager.GetString("TimerServiceCheckQuestionText2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** Uninstalling &apos;{0}&apos; solution... {1} *****.
        /// </summary>
        internal static string UninstallBegin {
            get {
                return ResourceManager.GetString("UninstallBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** Uninstall Failed {0} *****.
        /// </summary>
        internal static string UninstallError {
            get {
                return ResourceManager.GetString("UninstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {SolutionTitle} is removed.
        /// </summary>
        internal static string UninstallSubTitle {
            get {
                return ResourceManager.GetString("UninstallSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** Uninstall Successfully Completed {0} *****.
        /// </summary>
        internal static string UninstallSuccess {
            get {
                return ResourceManager.GetString("UninstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling.
        /// </summary>
        internal static string UninstallTitle {
            get {
                return ResourceManager.GetString("UninstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistering version number..
        /// </summary>
        internal static string UnregisterVersionNumberCommand {
            get {
                return ResourceManager.GetString("UnregisterVersionNumberCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** Upgrading &apos;{0}&apos; solution... {1} *****.
        /// </summary>
        internal static string UpgradeBegin {
            get {
                return ResourceManager.GetString("UpgradeBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** Upgrade Failed {0} *****.
        /// </summary>
        internal static string UpgradeError {
            get {
                return ResourceManager.GetString("UpgradeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating job for upgrading the solution on all applicable web applications..
        /// </summary>
        internal static string UpgradeSolutionCmd {
            get {
                return ResourceManager.GetString("UpgradeSolutionCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {SolutionTitle} is upgraded.
        /// </summary>
        internal static string UpgradeSubTitle {
            get {
                return ResourceManager.GetString("UpgradeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** Upgrade Successfully Completed {0} *****.
        /// </summary>
        internal static string UpgradeSuccess {
            get {
                return ResourceManager.GetString("UpgradeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading.
        /// </summary>
        internal static string UpgradeTitle {
            get {
                return ResourceManager.GetString("UpgradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for solution deployment job to complete. Press Abort to stop..
        /// </summary>
        internal static string WaitForSolutionDeployment {
            get {
                return ResourceManager.GetString("WaitForSolutionDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for solution retraction job to complete. Press Abort to stop..
        /// </summary>
        internal static string WaitForSolutionRetraction {
            get {
                return ResourceManager.GetString("WaitForSolutionRetraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for solution upgrade job to complete. Press Abort to stop..
        /// </summary>
        internal static string WaitForSolutionUpgrade {
            get {
                return ResourceManager.GetString("WaitForSolutionUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint 2007.
        /// </summary>
        internal static string WelcomeVersion2007 {
            get {
                return ResourceManager.GetString("WelcomeVersion2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint 2010.
        /// </summary>
        internal static string WelcomeVersion2010 {
            get {
                return ResourceManager.GetString("WelcomeVersion2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows SharePoint Service 3.0 is NOT installed!.
        /// </summary>
        internal static string WssCheckErrorText {
            get {
                return ResourceManager.GetString("WssCheckErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Foundation 2010 is NOT installed!.
        /// </summary>
        internal static string WssCheckErrorText2010 {
            get {
                return ResourceManager.GetString("WssCheckErrorText2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows SharePoint Service 3.0 is installed..
        /// </summary>
        internal static string WssCheckOkText {
            get {
                return ResourceManager.GetString("WssCheckOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Foundation 2010 is installed..
        /// </summary>
        internal static string WssCheckOkText2010 {
            get {
                return ResourceManager.GetString("WssCheckOkText2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Windows SharePoint Service 3.0 installed?.
        /// </summary>
        internal static string WssCheckQuestionText {
            get {
                return ResourceManager.GetString("WssCheckQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is SharePoint Foundation 2010 installed?.
        /// </summary>
        internal static string WssCheckQuestionText2010 {
            get {
                return ResourceManager.GetString("WssCheckQuestionText2010", resourceCulture);
            }
        }
    }
}
